#!/usr/bin/env python
# Copyright (C) 2009-2013 Bernd Feige
# This file is part of avg_q and released under the GPL v3 (see avg_q/COPYING).

import sys
import os
import avg_q
import avg_q.trgfile
import avg_q.paradigm
from avg_q.avg_q_file import formats_and_extensions

a=avg_q.avg_q()
for filename in sys.argv[1:]:
 parts=filename.split(':')
 if len(parts)==2 and parts[0] in dict(formats_and_extensions):
  filetype,filename=parts
 else:
  filetype=None
 if not os.path.exists(filename):
  print("Oops, %s doesn't exist - skipping..." % filename)
  continue
 base,ext=os.path.splitext(filename)
 if filetype is None and ext in ['.trg','.crs','.tri']:
  # Assume trigger file
  trg=avg_q.trgfile.trgfile(filename)
 else:
  infile=avg_q.avg_q_file(filename,filetype)
  trg=a.get_filetriggers(infile)
 triggers=trg.gettuples()
 trg.close()
 sfreq=trg.preamble.get('Sfreq')
 if sfreq:
  p=avg_q.paradigm.paradigm(triggers,float(sfreq))
 else:
  p=avg_q.paradigm.paradigm(triggers)
 stats=p.triggerstats()
 for code in stats:
  result=stats[code]
  if result.n<=1:
   print("%s Code %d: %d" % (filename, code, result.n))
  elif result.n==2:
   print("%s Code %d: %d [single diff %g]" % (filename, code, result.n, result.mean))
  else:
   print("%s Code %d: %d [mean %g+-%g, q0=%g q25=%g q50=%g q75=%g q100=%g]" % (filename, code, result.n, result.mean, result.sd, result.min, result.q25, result.q50, result.q75, result.max))
 if not stats:
  print("%s: No triggers!" % filename)
a.close()
